image: maven:3.9.1-amazoncorretto-17-debian

stages:
  - build
  - test
  - deploy
  - docker-build

cache:
  paths:
    - ~/.m2/

build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
  tags:
    - group-runner

test:
  stage: test
  script:
    - mvn test
  tags:
    - group-runner

deploy:
  stage: deploy
  script:
    - mvn spring-boot:run
  only:
    - master
  tags:
    - group-runner

docker-build:
  variables:
    CI_REGISTRY_IMAGE: "hello-world"
  image: docker:23.0.5-dind-alpine3.17
  stage: docker-build
  services:
    - docker:19.03.8-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - main
  tags:
    - group-runner