image: harbor.server.local/library/maven:3.9.1-amazoncorretto-17-debian

stages:
  - build
  - test
  - deploy
  - docker-build

cache:
  paths:
    - ~/.m2/
    - ~/cache

build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
  tags:
    - group-runner
  only:
    - dev

test:
  stage: test
  script:
    - mvn test
  tags:
    - group-runner
  only:
    - dev

deploy:
  stage: deploy
  script:
    - mvn spring-boot:run
  only:
    - master
  tags:
    - group-runner

docker-build:
  variables:
    CI_REGISTRY_IMAGE: "hello-world"
    CI_REGISTRY: "https://index.docker.io/v1/"
  stage: docker-build
#  image: harbor.server.local/library/moby/buildkit:buildx-stable-1
  image: harbor.server.local/library/docker:23.0.5-dind-alpine3.17
#  services:
#    - harbor.server.local/library/docker:23.0.5-dind-alpine3.17
  script:
    - export DOCKER_HOST=192.168.31.13
#    - export DOCKER_BUILDKIT=1
#    - export DOCKER_CLI_EXPERIMENTAL=enabled
#    - docker buildx create --use
#    - docker buidx build -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --cache-from=type=local,src=./cache --cache-to=type=local,dest=./cache --load .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD ${CI_REGISTRY}
#    - docker buildx build --network host -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker build --network host -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - main
  tags:
    - group-runner