image: maven:3.9.1-amazoncorretto-17-debian

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - ~/.m2/

build:
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
  tags:
    - group-runner

test:
  stage: test
  script:
    - mvn test
  tags:
    - group-runner

deploy:
  stage: deploy
  script:
    - mvn spring-boot:run
  only:
    - main
  tags:
    - group-runner
