stages:
  - install
  - build
  - deploy

install_job:
  stage: install
  script:
    - echo 'hello install'

build_job:
  stage: build
  script:
    - echo 'hello build'

deploy_job:
  stage: deploy
  script:
    - echo 'hello deploy'