# docker build -t harbor.server.local/library/docker-buildkit:23.0.5-dind-alpine3.17 -f Dockerfile.buildkit .
# docker push harbor.server.local/library/docker-buildkit:23.0.5-dind-alpine3.17
FROM harbor.server.local/library/docker:23.0.5-dind-alpine3.17

RUN docker buildx install