# docker build -t harbor.server.local/library/moby/buildkit-ca:buildx-stable-1 -f Dockerfile.buildkit .
# docker push harbor.server.local/library/moby/buildkit-ca:buildx-stable-1
FROM harbor.server.local/library/moby/buildkit:buildx-stable-1

COPY ./certs/ca.crt /etc/ssl/certs/ca-certificates/ca.pem